# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rubygem-hammer_cli.spec

# add or remove files that should be synced
files_to_sync:
    - rubygem-hammer_cli.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: hammer_cli
# downstream (Fedora) RPM package name
downstream_package_name: rubygem-hammer_cli

actions:
  post-upstream-clone:
    - "wget https://raw.githubusercontent.com/theforeman/foreman-packaging/rpm/develop/packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec -O rubygem-hammer_cli.spec"
    - "a2x -d manpage -f manpage -D man/ man/hammer.1.asciidoc"
    - "gzip -f9 man/hammer.1"
    - "sed -i '/^%global prereleasesource pre.develop$/d' rubygem-hammer_cli.spec"
    - "sed -i '/^%global prerelease %{?prereleasesource:.}%{?prereleasesource}$/d' rubygem-hammer_cli.spec"
  get-current-version:
    - ruby -rrubygems -e 'puts Gem::Specification::load(Dir.glob("*.gemspec").first).version'
  create-archive:
    - gem build hammer_cli.gemspec
    - bash -c "ls -1t ./hammer_cli-*.gem | head -n 1"

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      rhel-8:
        additional_modules: "foreman-devel:el8"
        additional_repos:
          - https://yum.theforeman.org/releases/nightly/el8/x86_64/
          - https://yum.theforeman.org/plugins/nightly/el8/x86_64/
      rhel-9:
        additional_modules: "foreman-devel:el9"
        additional_repos:
          - https://yum.theforeman.org/releases/nightly/el9/x86_64/
          - https://yum.theforeman.org/plugins/nightly/el9/x86_64/
    module_hotfixes: true

srpm_build_deps:
  - wget
  - asciidoc
  - gzip
  - rubygems
