#!/usr/bin/env ruby
# Copyright (C) 2011 Vijay Brian Gupta brian.gupta@brandorr.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
# USA.

require "rubygems"
require "rest_client"
require "json"
require "yaml"
require "clamp"

module Hammer

  class ForemanResource
    
    def get_collection(path, options = {})
      JSON.parse(RestClient::Request.new({:method  => :get,
                                     :url     => "#{@foreman_url}/#{path.to_s.chomp('/')}",
                                     :user    => @foreman_user, :password => @foreman_pass,
                                     :headers => { :accept => :json, :content_type => :json }}.merge(options)).execute.to_s)
    end

#    def search_collection(path,search)
#      get_collection(path, :url => "#{@foreman_url}/#{path}?search=#{URI.encode(search)}")
#    end

  end

  class HammerCommand < Clamp::Command

    option ["-d", "--debug"], :flag, "Output more information"
    option ["-u", "--user"], "USER", "Foreman user"
    option ["-p", "--pass"], "PASSWORD", "Foreman password"
    option ["-s", "--server"], "URL", "Foreman Server URL", :default => "http://localhost/"
    option "--json", :flag, "JSON output"
    option "--yaml", :flag, "YAML output"
    option "--version", :flag, "show version" do
      puts "hammer-1.0.0"
      exit(0)
    end

#    def initialize
#      @foreman_user = user
#      @foreman_pass = pass
#      @foreman_url  = server
#      @usejson      = json?
#      @useyaml      = yaml?

#      RestClient.log = 'stdout' if debug?
#debugging lines
#      puts @foreman_user
#      puts "json" if @usejson
#    end
  end

  class DomainListCommand < HammerCommand
    def execute
      puts "Domain list here."
      #raise NotImplementedError
    end
  end

  class DomainShowCommand < HammerCommand
    def execute
      puts "Domain show here."
      #raise NotImplementedError
    end
  end

  class DomainCreateCommand < HammerCommand
    def execute
      puts "Domain create here."
      #raise NotImplementedError
    end
  end

  class DomainDeleteCommand < HammerCommand
    def execute
      puts "Domain delete here."
      #raise NotImplementedError
    end
  end

  class DomainUpdateCommand < HammerCommand
    def execute
      puts "Domain update here."
      #raise NotImplementedError
    end
  end

  class DomainCommand < HammerCommand
    subcommand "list", "List domains.", DomainListCommand
    subcommand "show", "Show domains.", DomainShowCommand
    subcommand "create", "Create domains.", DomainCreateCommand
    subcommand "delete", "Delete domains.", DomainDeleteCommand
    subcommand "update", "Update domains.", DomainUpdateCommand
  end

  class EnvironmentListCommand < HammerCommand
    def execute
      puts "Environment list here."
      #raise NotImplementedError
    end
  end

  class EnvironmentShowCommand < HammerCommand
    def execute
      puts "Environment show here."
      #raise NotImplementedError
    end
  end

  class EnvironmentCreateCommand < HammerCommand
    def execute
      puts "Environment create here."
      #raise NotImplementedError
    end
  end

  class EnvironmentDeleteCommand < HammerCommand
    def execute
      puts "Environment delete here."
      #raise NotImplementedError
    end
  end

  class EnvironmentUpdateCommand < HammerCommand
    def execute
      puts "Environment update here."
      #raise NotImplementedError
    end
  end

  class EnvironmentCommand < HammerCommand
    subcommand "list", "List environments.", EnvironmentListCommand
    subcommand "show", "Show environments.", EnvironmentShowCommand
    subcommand "create", "Create environments.", EnvironmentCreateCommand
    subcommand "delete", "Delete environments.", EnvironmentDeleteCommand
    subcommand "update", "Update environments.", EnvironmentUpdateCommand
  end

  class HostListCommand < HammerCommand
    def execute
      puts "Host list here."
      puts user
      puts "json" if json?
      #raise NotImplementedError
    end
  end

  class HostShowCommand < HammerCommand
    def execute
      puts "Host show here."
      #raise NotImplementedError
    end
  end

  class HostCreateCommand < HammerCommand
    def execute
      puts "Host create here."
      #raise NotImplementedError
    end
  end

  class HostDeleteCommand < HammerCommand
    def execute
      puts "Host delete here."
      #raise NotImplementedError
    end
  end

  class HostUpdateCommand < HammerCommand
    def execute
      puts "Host update here."
      #raise NotImplementedError
    end
  end

  class HostCommand < HammerCommand
    subcommand "list", "List hosts.", HostListCommand
    subcommand "show", "Show hosts.", HostShowCommand
    subcommand "create", "Create hosts.", HostCreateCommand
    subcommand "delete", "Delete hosts.", HostDeleteCommand
    subcommand "update", "Update hosts.", HostUpdateCommand
  end


  class MainCommand < HammerCommand

    subcommand "domain", "Work with domains.", DomainCommand
    subcommand "environment", "Work with environments.", EnvironmentCommand
    subcommand "host", "Work with hosts.", HostCommand
#    subcommand "exec", "Work with hostgroups.", HostgroupCommand
#    subcommand "help", "Work with hostgroups.", HostgroupCommand
#    subcommand "search", "Work with hostgroups.", HostgroupCommand
#    subcommand "status", "Work with hostgroups.", HostgroupCommand
#    subcommand "dns", "Work with hostgroups.", HostgroupCommand
#    subcommand "dhcp", "Work with hostgroups.", HostgroupCommand
#    subcommand "tftp", "Work with hostgroups.", HostgroupCommand
#    subcommand "puppetca", "Work with hostgroups.", HostgroupCommand
#    subcommand "puppet", "Work with hostgroups.", HostgroupCommand
#    subcommand "server", "Work with hostgroups.", HostgroupCommand

  end

end

Hammer::MainCommand.run
