#
# Makefile for PO merging and MO generation. More info in the README.
#
# Run make help to list available targets
#
include $(shell bundle exec ruby -e 'require "hammer_cli"; puts HammerCLI::I18n.main_makefile')
