name: Run tests GA

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hammer-cli
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'

    steps:
      - name: Get hammer-cli
        uses: actions/checkout@v2
        with:
          path: hammer-cli
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: hammer-cli
      - name: Run tests
        run: |
          bundle exec rake test
